# Generated by Django 5.0.14 on 2025-09-12 15:56

import accounts.models
import django.db.models.deletion
import django.utils.timezone
import utilities.idx
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=utilities.idx.generate_otp_id, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('ref', models.TextField()),
                ('device_identity', models.CharField(max_length=255)),
                ('otp', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether the OTP has been verified.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OTP Request',
                'verbose_name_plural': 'OTP Requests',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.CharField(default=utilities.idx.generate_user_id, editable=False, max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('email_verified', models.BooleanField(default=False, help_text='Designates whether the email has been verified.', verbose_name='email verified')),
                ('firebase_uid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='HostAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=utilities.idx.generate_host_id, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether the host account has been verified.')),
                ('identity_type', models.CharField(choices=[('bvn', 'BVN'), ('nin', 'NIN'), ('passport', 'National Passport')], max_length=50, verbose_name='Identity Type')),
                ('identity_image', models.ImageField(max_length=255, upload_to=accounts.models.upload_identity_image, verbose_name='Identity Shot')),
                ('host_photo', models.ImageField(max_length=255, upload_to=accounts.models.upload_host_image, verbose_name='Host Photo')),
                ('identity_number', models.CharField(help_text='Unique number for the identity.', max_length=100, unique=True, verbose_name='Identity Number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='host_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Host Account',
                'verbose_name_plural': 'Host Accounts',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=utilities.idx.generate_phone_number_id, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone_number', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phone Number',
                'verbose_name_plural': 'Phone Numbers',
            },
        ),
    ]
