# Generated by Django 5.0.14 on 2025-08-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether the OTP has been verified.'),
        ),
        migrations.AlterField(
            model_name='stakeholderaccount',
            name='identity_type',
            field=models.CharField(choices=[('bvn', 'BVN'), ('nin', 'NIN'), ('passport', 'National Passport')], max_length=50, verbose_name='Identity Type'),
        ),
        migrations.AlterField(
            model_name='stakeholderaccount',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether the stakeholder account has been verified.'),
        ),
    ]
