# Generated by Django 5.0.14 on 2025-05-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprequest',
            name='device_identity',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
