# Generated by Django 5.0.14 on 2025-05-02 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_phonenumber_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govissuedidentity',
            name='stakeholder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity', to='accounts.stakeholderaccount'),
        ),
    ]
