# Generated by Django 5.0.14 on 2025-05-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_govissuedidentity_stakeholder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='govissuedidentity',
            options={'verbose_name': 'Gov Issued Identity', 'verbose_name_plural': 'Gov Issued Identities'},
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Designates whether the email has been verified.', verbose_name='email verified'),
        ),
    ]
