# Generated by Django 5.0.14 on 2025-05-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_govissuedidentity_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otprequest',
            name='email',
        ),
        migrations.AddField(
            model_name='otprequest',
            name='ref',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
