services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.staging
    container_name: deduke-backend-staging
    restart: unless-stopped
    expose:
      - 8000
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env.staging
    depends_on:
      db:
        condition: service_healthy
  # frontend:
  #     build:
  #       context: ./frontend
  #       dockerfile: Dockerfile.staging
  #     container_name: deduke-frontend-staging
  #     restart: unless-stopped
  #     expose:
  #       - 3000
  #     # env_file:
  #     #   - ./frontend/.env.staging
  #     depends_on:
  #       backend:
  #         condition: service_started
  db:
    image: postgis/postgis:latest
    container_name: deduke-db-staging
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  traefik:
    image: traefik:v3.5
    container_name: deduke-traefik-staging
    restart: unless-stopped
    ports:
      - "80:80"
      # - "443:443"
      - "8080:8080"  # Traefik dashboard (remove in production)
    volumes:
      - ./traefik/staging/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/staging/dynamic:/etc/traefik/dynamic:ro
      - letsencrypt:/etc/letsencrypt
        
    depends_on:
      - backend
      # - frontend

volumes:
  db-data:
  letsencrypt:

secrets:
  db-password:
    file: db/.secrets/password.staging.txt