services:
  backend:
    build:
      context: ./backend
    container_name: backend-stagging
    command: >
      sh -c "python manage.py migrate
      && python manage.py collectstatic --noinput
      && daphne main.asgi:application -b 0.0.0.0 -p 8000"
    restart: unless-stopped
    expose:
      - 8000
    volumes:
      - ./backend:/app
    env_file:
      - .env_file/stagging.env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    container_name: db-stagging
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres #TODO: make sure to use your prefered db name
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-stagging
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Mount the base configuration
      - ./nginx/nginx-stagging.conf:/etc/nginx/conf.d/default.conf  # Mount the staging configuration
      - ./nginx/certs/:/etc/nginx/certs/  # Mount the directory for SSL certificates
      - ./backend/staticfiles:/app/staticfiles
      # - ./backend/mediafiles:/app/mediafiles
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      
    depends_on:
      backend:
        condition: service_started
  certbot:
    image: certbot/certbot:latest
    container_name: certbot-stagging
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./nginx/nginx-stagging.conf:/etc/nginx/conf.d/default.conf
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done;'" # Renew certificates periodically (every 12 hours)

volumes:
  db-data:
  certbot-etc:
  certbot-var:
secrets:
  db-password:
    file: .secrets/db/password-stagging.txt

