services:
  backend:
    build:
      context: ./backend
    container_name: backend-dev
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    ports:
      - 8001:8000
    volumes:
      - ./backend:/app
    env_file:
      - .env_file/dev.env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgis/postgis:latest
    container_name: db-dev
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres #TODO: make sure to use your prefered db name
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
secrets:
  db-password:
    file: .secrets/db/password-dev.txt
