# Generated by Django 5.0.14 on 2025-05-24 10:03

import utilities.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to=utilities.helpers.property_image_upload_handler),
        ),
    ]
