# Generated by Django 5.0.14 on 2025-08-27 08:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestedProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_properties', to='properties.property')),
                ('responder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_interested_properties', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interested Property',
                'verbose_name_plural': 'Interested Properties',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InterestedPropertyDialog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interested_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogs', to='properties.interestedproperty')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_interested_property_dialogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interested Property Dialog',
                'verbose_name_plural': 'Interested Property Dialogs',
                'ordering': ['-created_at'],
            },
        ),
    ]
