# Generated by Django 5.0.14 on 2025-10-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedproperty',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verifiedproperty',
            name='verification_phase',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Phase 1', 'Phase 1'), ('Phase 2', 'Phase 2'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='architectural_style',
            field=models.CharField(blank=True, choices=[('Modern', 'Modern'), ('Traditional', 'Traditional'), ('Industrial', 'Industrial')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='commercial_type',
            field=models.CharField(choices=[('Office', 'Office'), ('Shop', 'Shop'), ('Home', 'Home'), ('land', 'Land')], max_length=50),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='property_condition',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Under Renovation', 'Under Renovation'), ('Under Construction', 'Under Construction'), ('Bank Owned', 'Bank Owned')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shortletproperty',
            name='shortlet_type',
            field=models.CharField(choices=[('Hostel', 'Hostel'), ('Hotel', 'Hotel'), ('1 Bedroom', '1 Bedroom'), ('2 Bedroom', '2 Bedroom'), ('3 Bedroom', '3 Bedroom')], max_length=50),
        ),
    ]
