# Generated by Django 5.0.14 on 2025-10-12 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_verifiedproperty_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedproperty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bannedproperty',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banned', to='properties.property'),
        ),
    ]
