# Generated by Django 5.0.14 on 2025-09-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_interestedproperty_interestedpropertydialog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interestedpropertydialog',
            options={'ordering': ['created_at'], 'verbose_name': 'Interested Property Dialog', 'verbose_name_plural': 'Interested Property Dialogs'},
        ),
    ]
