# Generated by Django 5.0.14 on 2025-10-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_verifiedproperty_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannedproperty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
