# Generated by Django 5.0.14 on 2025-10-12 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_bannedproperty_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannedproperty',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banned', to='properties.property'),
        ),
    ]
