# Generated by Django 5.0.14 on 2025-09-12 15:56

import django.db.models.deletion
import utilities.idx
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(default=utilities.idx.generate_payment_id, editable=False, help_text='Payment ID from the payment gateway (e.g., Flutterwave).', max_length=255, primary_key=True, serialize=False)),
                ('unit_amount', models.IntegerField(help_text='Amount in the smallest currency unit')),
                ('currency', models.CharField(default='NGN', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.CharField(default=utilities.idx.generate_checkout_id, editable=False, help_text='A weak identifier for the checkout session. Default is a {idx.generate_checkout_id}.', max_length=255, primary_key=True, serialize=False)),
                ('payment_gateway', models.CharField(choices=[('flutterwave', 'Flutterwave')], max_length=100)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('completed', 'Completed'), ('failed', 'Failed')], default='initiated', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkout', to='payments.payment')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyCheckout',
            fields=[
                ('checkout_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.checkout')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Checkout',
                'verbose_name_plural': 'Property Checkouts',
                'ordering': ['-created_at'],
            },
            bases=('payments.checkout',),
        ),
    ]
