http:
  # Add the router for HTTPS
  routers:
    backend-secure:
      entryPoints:
        - websecure
      service: backend
      rule: Host(`de-duke.com`) || Host(`www.de-duke.com`)
      tls:
        certResolver: letsencrypt
    
    # HTTP router with redirect to HTTPS
    backend-redirect:
      entryPoints:
        - web
      service: backend
      rule: Host(`de-duke.com`) || Host(`www.de-duke.com`)
      middlewares:
        - redirect-to-https
    
    # Separate router for EC2 hostname without SSL
    backend-insecure:
      entryPoints:
        - web
      service: backend
      rule: Host(`ec2-13-42-130-253.eu-west-2.compute.amazonaws.com`)

  # Add middlewares
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

  # Add the service
  services:
    backend:
      loadBalancer:
        servers:
          - url: http://backend:8000
        passHostHeader: false