http:
  # Add the router
  routers:
    backend:
      entryPoints:
        - web
      service: backend
      rule: Host(`de-duke.com`) || Host(`www.de-duke.com`)
      # rule: Host(`backend.vanguardhosting.local`)
      tls:
        certResolver: letsencrypt
    
    backend-insecure:
      entryPoints:
        - web
      service: backend
      rule: Host(`ec2-35-179-76-99.eu-west-2.compute.amazonaws.com`)
    # frontend:
    #   entryPoints:
    #     - web
    #   service: frontend
    #   rule: Host(`vanguardhosting.local`)

  # Add the service
  services:
    backend:
      loadBalancer:
        servers:
          - url: http://backend:8000
        passHostHeader: false
    # frontend:
    #   loadBalancer:
    #     servers:
    #       - url: http://frontend:3000
    #     passHostHeader: false